### ISSUE TITLE
Event Manager: arrange horizontally

### ISSUE THREAD

**Issue by humdingerb** [AkshayAgarwal007/Calendar#10]
Currently the window is very tall, because everything's arranged vertically.
As most people have wide screen monitors, putting the Start/End time and Recurrance to the right of the Name/Place would be better.

**Comment by AkshayAgarwal007** [comment]
@humdingerb  I have a few more questions..
1. Is it(event manager) fine as a separate window or do I include it inside the MainWindow as in initial mockups.
2. What do I do about the DateTimeEdit thing?
3. The event list items in DayView seems to have issue with displaying category indicator when the scrolling is activated. 
4. It will be also nice if you can review the code in general.

**Comment by humdingerb** [comment]
> 1. Is it(event manager) fine as a separate window or do I include it inside the MainWindow as in initial mockups.

I like having the main window as minimal as possible. So the extra window for adding/editing events is fine.

> 2. What do I do about the DateTimeEdit thing?

Not sure I understand. You mean what I wrote about arranging horizontally?
Just put the Start/End time and Recurrance in a "Group" and arrange it and the Name/Place/Description group horizontally.

> 3. The event list items in DayView seems to have issue with displaying category indicator when the scrolling is activated.

No idea at the moment... It would help if Calendar would save events and I wouldn't have to create a dowen events every time Calendar is launched... :)

> 4. It will be also nice if you can review the code in general.

I'm not much of a coder. Everything takes me ages to get right. Your mentors are much better suited for that. If I see anything, I let you know, but generally I come more from the user/usability perspective...

**Comment by AkshayAgarwal007** [comment]
Thanks.

1. I was asking regarding a DateTimeEdit(something like a QDateTimeEdit widget in Qt) control in order to selected start/end date and time. The closest thing I could find to a DateTimeEdit in haiku is the one used in the time preferences but I think it would not be good for the Calendar app. I would be working to implement a DateTimeEdit control later but if there's any such widget that can be used for now or any ideas regarding the same.

2.  Regarding saving of events, I am working on it and Google calendar integration too. :) :)

**Comment by humdingerb** [comment]
WRT working on a widget, you have to discuss that with your mentors. If you decide to move the Calendar app forward, I think for a first quick&dirty solution, a textcontrol for the user to enter the time manually is OK.

**Comment by scottmc** [comment]
Yeah short term a text control might suffice.  Perhaps creating a full blown calendar widget would make for a nice GCI task.

**Comment by AkshayAgarwal007** [comment]
Cool.

**Comment by AkshayAgarwal007** [comment]
Is this fine?

![event_manager](https://user-images.githubusercontent.com/8170214/28890314-45bef296-77e4-11e7-8ed7-1f7b6a685f6e.png)

**Comment by smccrearyx** [comment]
For Recurrence I would think you'd also want Daily and/or Weekly.  But yes in general this looks fine.

**Comment by humdingerb** [comment]
Nice! If "Recurrence" accrues more options, a pop-up menu would be more appropriate. Then "Recurrence" can become its label and there's no need for the BBox. Maybe the "All day" checkbox should be moved to the top of the right side, as it's related to the Start/End times.

**Comment by AkshayAgarwal007** [comment]
![cal2](https://user-images.githubusercontent.com/8170214/28966681-3f7c0fac-7935-11e7-9e22-ac7ec5db6d5a.png)
