### ISSUE TITLE
Event Manager: Button labels

### ISSUE THREAD

**Issue by humdingerb** [AkshayAgarwal007/Calendar#11]
I think having "Delete" (left-aligned), "Cancel" (right-aligned) and "OK" (right-aligned) would be more standard. Putting the "Delete" to the left avoids accidental clicks...

**Comment by AkshayAgarwal007** [comment]
Fixed here.
https://github.com/AkshayAgarwal007/Calendar/commit/d6930ab3a37e634163b39849eae6684434483f03

![cal2](https://user-images.githubusercontent.com/8170214/28966936-6f82bf60-7936-11e7-9ab7-001c2ab23aa4.png)
