### ISSUE TITLE
Event Manager window location

### ISSUE THREAD

**Issue by Perelandra0x309** [AkshayAgarwal007/Calendar#17]
I just noticed that on my laptop (screen resolution 1200 X 800) when I click "Add Event" the lower half of the Event Manager window is below the bottom of the screen.  There should be a check to make sure the window is on screen, if not maybe call CenterOnScreen()?

Also would be nice if the user moves the window that the position is saved so it always is in the same location.  If I move it a new event always opens in the current default location.

**Comment by AkshayAgarwal007** [comment]
I've fixed it. All the windows(event manager, category manager etc.) are now positioned on the center of screen.
Regarding saving the position... Do I do this for all the widows like even for category manager and category edit window?

**Comment by Perelandra0x309** [comment]
That would be nice, that way I could for example position the event manager window just to the left of the main window and have it always open to the same location.  That way I can see all the other events for that day if scheduling time I can check for conflicts.
