### ISSUE TITLE
Unset file before deleting object?

### ISSUE THREAD

**Issue by Perelandra0x309** [AkshayAgarwal007/Calendar#20]
Maybe others can weigh in but I usually call file->Unset() before deleting a BFile object.  For example here:
https://github.com/AkshayAgarwal007/Calendar/blob/master/src/Preferences.cpp#L62

**Comment by AkshayAgarwal007** [comment]
Unset() calls BNode::close_fd() which is automatically called when a BFile object is destroyed?
https://github.com/haiku/haiku/blob/master/src/kits/storage/File.cpp#L354-L358

**Comment by Perelandra0x309** [comment]
OK maybe I'm just paranoid :-)
