### ISSUE TITLE
Keep the current day in calendar view highlighted on change in selected day.

### ISSUE THREAD

**Issue by AkshayAgarwal007** [AkshayAgarwal007/Calendar#3]

**Comment by AkshayAgarwal007** [comment]
Fixed here:
https://github.com/haiku/haiku/commit/8013f2e07d73a3b754629cac1798f059ec20c38d
https://github.com/haiku/haiku/commit/b32b6a8633ac957ecc34f78c124768a4735f61f6

**Comment by scottmc** [comment]
Time travel?  Supposed to be working on a Calendar App, not a time machine.
;)

**Comment by AkshayAgarwal007** [comment]
Will be very careful with the system time while making commits from now on.
